export const FETCH_FILMS_START = "FETCH_FILMS_START";
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";

export const ADD_FILM_START = "ADD_FILM_START";
export const ADD_FILM_SUCCESS = "ADD_FILM_SUCCESS";
export const ADD_FILM_FAILURE = "ADD_FILM_FAILURE";

export const DELETE_FILM_START = "DELETE_FILM_START";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILM_FAILURE = "DELETE_FILM_FAILURE";

export const REMOVE_FILM = "REMOVE_NOTE";
export const CHANGE_FILTER = "CHANGE_FILTER";
